version = 0.1
[default.deploy.parameters]
stack_name = "mtjs-websocket-backend"
resolve_s3 = true
s3_prefix = "mtjs-websocket-backend"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []

[default.local_invoke.parameters]
# parameter_overrides removed for AWS deployment